config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-chocolate-gopher.sh
        container: qc.acc_wimpy-eggplant-whippet
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-lilac-millipede.sh
        container: qc.doc_homely-charcoal-cassowary
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-ultramarine-bloodhound.sh
        container: qc.doc_ugly-saffron-ferret
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-vermilion-cow.sh
        container: qc.doc_cloudy-red-dodo
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-mauve-neanderthal.sh
        container: qc.lic_shabby-mustard-tortoise
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-red-panda.sh
        container: qc.sec_homely-amethyst-bandicoot
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-white-javanese.sh
        container: qc.sty_paltry-gold-hyena
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-sepia-wildebeest.sh
        container: qc.uni_freaky-brass-falcon
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-alizarin-squid.sh
        container: qc.ver_woozy-saffron-baboon
timeout: 5400
