config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-chestnut-tamarin.sh
        container: qc.acc_chummy-bistre-deer
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-xanthic-civet.sh
        container: qc.doc_muzzy-wisteria-mist
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-teal-insect.sh
        container: qc.doc_geeky-tangerine-shark
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-charcoal-gopher.sh
        container: qc.doc_scanty-magenta-wombat
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-asparagus-spoonbill.sh
        container: qc.lic_pretty-vermilion-mau
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-orange-chimpanzee.sh
        container: qc.sec_pokey-persimmon-earwig
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-gold-capybara.sh
        container: qc.sty_muggy-turquoise-nightingale
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-black-mau.sh
        container: qc.uni_trippy-persimmon-woodpecker
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-bistre-llama.sh
        container: qc.ver_frumpy-jade-fly
timeout: 5400
