config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-ecru-dachshund.sh
        container: qc.acc_pokey-chestnut-jellyfish
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-linen-rattlesnake.sh
        container: qc.doc_crabby-champagne-beetle
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-teal-goose.sh
        container: qc.doc_cranky-tangerine-mouse
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-razzmatazz-bonobo.sh
        container: qc.doc_beady-tomato-mongoose
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olivine-newfoundland.sh
        container: qc.lic_homely-cyan-civet
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-seashell-vole.sh
        container: qc.sec_ready-aquamarine-bandicoot
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-mustard-ragdoll.sh
        container: qc.sty_boozy-celadon-dane
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-thistle-moose.sh
        container: qc.uni_flabby-flax-newt
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-indigo-chin.sh
        container: qc.ver_baggy-charcoal-retriever
timeout: 5400
