config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-gold-panda.sh
        container: qc.acc_foggy-celadon-foxhound
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-mauve-wombat.sh
        container: qc.doc_gamy-cerulean-tamarin
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-azure-abyssinian.sh
        container: qc.doc_bumpy-vermilion-mole
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-yellow-chamois.sh
        container: qc.doc_scanty-buff-pinscher
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-heliotrope-starfish.sh
        container: qc.lic_tacky-firebrick-turkey
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-tomato-wallaby.sh
        container: qc.sec_greasy-ruby-chameleon
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-sangria-chow.sh
        container: qc.sty_surly-sepia-hyena
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rust-mayfly.sh
        container: qc.uni_boozy-cinnabar-caiman
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-lemon-salamander.sh
        container: qc.ver_flabby-rust-fowl
timeout: 5400
