config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-burgundy-molly.sh
        container: qc.acc_tasty-denim-magpie
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-beige-koala.sh
        container: qc.doc_craggy-black-lionfish
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-periwinkle-uakari.sh
        container: qc.doc_cheeky-ochre-bracke
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-black-moth.sh
        container: qc.doc_wimpy-aqua-magpie
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-xanthic-stoat.sh
        container: qc.lic_lanky-yellow-beaver
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-corn-wolfhound.sh
        container: qc.sec_frumpy-burgundy-axolotl
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-platinum-caterpillar.sh
        container: qc.sty_lumpy-violet-discus
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-beige-barb.sh
        container: qc.uni_surly-malachite-skunk
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-azure-termite.sh
        container: qc.ver_boozy-emerald-buzzard
timeout: 5400
