config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testing-notebooks:
      branch: main
      repo: https://github.com/PalomoIFCA/testing-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cinnabar-penguin.sh
        container: qc.acc_sickly-ecru-chimpanzee
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testing-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-champagne-affenpinscher.sh
        container: qc.doc_sickly-myrtle-markhor
      github.com/PalomoIFCA/testing-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-razzmatazz-tamarin.sh
        container: qc.doc_lousy-magenta-rat
      github.com/PalomoIFCA/testing-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-charcoal-blue.sh
        container: qc.doc_scummy-copper-chinchilla
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testing-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-grey-ray.sh
        container: qc.lic_sleazy-olivine-bobcat
  QC.Sec:
    repos:
      github.com/PalomoIFCA/testing-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cyan-lionfish.sh
        container: qc.sec_gimpy-taupe-crocodile
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testing-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gamboge-octopus.sh
        container: qc.sty_blurry-gamboge-neanderthal
  QC.Uni:
    repos:
      github.com/PalomoIFCA/testing-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-smalt-newfoundland.sh
        container: qc.uni_skanky-pumpkin-capuchin
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testing-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-khaki-wrasse.sh
        container: qc.ver_lanky-burgundy-llama
timeout: 5400
